### ISSUE TITLE
Ветки условных ветвлений не отличаются друг от друга

### ISSUE THREAD

**Issue by maximgorbatyuk** [sammael86/interfaces#1]
https://github.com/sammael86/interfaces/blob/754c51cd4e38e8bd37f5b38bccc7c0b7e74b8a5a/NUnitTestProject1/UnitTest1.cs#L50

Ветки условных ветвлений не отличаются друг от друга. Зачем этот метод?

**Comment by sammael86** [comment]
Сначала планировалась немного другая реализация тестирования. Доделывалось в спешке. Сейчас исправлено.
